apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
labels:
  app: mosquitto
data:
  password.txt: |
    mqtt:$7$101$g7WomN/SGNPMeynw$tKcP3cUUCPVF5sbQ3si2ZK8o1j48HVvmpd88hy3nmdmonRJMRJFLb8W7p4DJkTRftXsfkt+8z52HN+Fev2FpHA==
    pai:$7$101$q5hhnuTJ6ORTXgyq$l4c+FulaXS9OYA3+1G3VoirhQOhikfQHJ0io8I33l31vTVak/ai9IVxK4yrrHRn4New2ebAaC8b48Pd4qtlVow==