apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pv-claim
labels:
  app: mosquitto
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi